//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectIHFFv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klant
    {
        public Klant()
        {
            this.Reservering = new HashSet<Reservering>();
        }

        public Klant(string emailadres, string voornaam, string achternaam, string telefoonnummer)
        {
            this.emailadres = emailadres;
            this.voornaam = voornaam;
            this.achternaam = achternaam;
            this.telefoonnummer = telefoonnummer; 
        }
    
        public int id { get; set; }
        public string emailadres { get; set; }
        public string voornaam { get; set; }
        public string achternaam { get; set; }
        public string telefoonnummer { get; set; }
    
        public virtual ICollection<Reservering> Reservering { get; set; }
    }
}
