//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectIHFFv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klant_reservering
    {
        public Klant_reservering(int reservering_id, int event_id, double? prijs, int aantal_personen)
        {
            this.reservering_id = reservering_id;
            this.event_id = event_id;
            this.prijs = prijs;
            this.aantal_personen = aantal_personen; 
        }
        public int id { get; set; }
        public Nullable<int> reservering_id { get; set; }
        public Nullable<int> event_id { get; set; }
        public Nullable<double> prijs { get; set; }
        public Nullable<int> aantal_personen { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Reservering Reservering { get; set; }
    }
}
