//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectIHFFv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locatie
    {
        public Locatie()
        {
            this.Event = new HashSet<Event>();
        }
    
        public int id { get; set; }
        public string capaciteit { get; set; }
        public string naam { get; set; }
        public string zaal { get; set; }
        public string straat { get; set; }
        public string huisnr { get; set; }
        public string toevoeging { get; set; }
        public string postcode { get; set; }
        public string plaats { get; set; }
    
        public virtual ICollection<Event> Event { get; set; }
    }
}
