//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectIHFFv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservering
    {
        public Reservering()
        {
            this.Klant_reservering = new HashSet<Klant_reservering>();
        }
    
        public int id { get; set; }
        public int klantid { get; set; }
        public Nullable<bool> is_betaald { get; set; }
        public Nullable<bool> is_geannuleerd { get; set; }
        public Nullable<System.DateTime> besteldatum { get; set; }
        public string ophaalcode { get; set; }
    
        public virtual Klant Klant { get; set; }
        public virtual ICollection<Klant_reservering> Klant_reservering { get; set; }
    }
}
